services:
  eerovista:
    build: .
    container_name: eerovista
    restart: unless-stopped
    ports:
      - "9080:8080"
      - "5353:53/udp"  # DNS server (exposed on host port 5353)
      - "5353:53/tcp"  # DNS server TCP
    volumes:
      - ./data:/data
    environment:
      # Database
      - DATABASE_PATH=/data/eerovista.db

      # Timezone for date/time display and daily bandwidth grouping
      # Use IANA timezone names (e.g., "America/Los_Angeles", "America/New_York", "Europe/London")
      - TZ=America/New_York

      # Collection intervals (seconds)
      - COLLECTION_INTERVAL_DEVICES=30
      - COLLECTION_INTERVAL_NETWORK=60

      # Data retention (days)
      - DATA_RETENTION_RAW_DAYS=7
      - DATA_RETENTION_HOURLY_DAYS=30
      - DATA_RETENTION_DAILY_DAYS=365

      # Logging
      - LOG_LEVEL=INFO

      # DNS Server Configuration (change domain to customize)
      - DNS_DOMAIN=eero.local
      - DNSMASQ_HOSTS_PATH=/etc/dnsmasq.d/eerovista.hosts

      # Optional: Pre-configured session token (normally set via web UI)
      # - EERO_SESSION_TOKEN=

      # Encryption key for secure token storage (persists across restarts)
      - ENCRYPTION_KEY=wOEc1gXtSGN9IcwaOduptVKt9HRnJRz6Ab1QNWOhRdQ=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
